### ISSUE TITLE
Azure Map Popup rendering issue

### ISSUE THREAD

**Issue by sangeetha321** [Azure/react-azure-maps#188] opened 2023-11-28 07:08 UTC
How can we position the popup at the bottom if I am at the top of the map? In the second image, the top part of the popup is not visible. Please refer to the screenshots
<img width="576" alt="1" src="https://github.com/Azure/react-azure-maps/assets/14287834/70b23da0-f26c-47a3-bbbd-86dfab720050">

<img width="576" alt="2" src="https://github.com/Azure/react-azure-maps/assets/14287834/3e45b634-724f-43fd-8c47-cba33ef821ff">

```
<AzureMapPopup
          isVisible={true}
          options={{
            position: [longitude,latitude],
            closeButton: false,
            pixelOffset: [-1, -32],
          }}
          popupContent={<div className="new-map-popup-node" id="popupNode" />}
        />
```

**Comment by yulinscottkang** [comment] 2023-11-30 07:09
The popup should automatically adjust its location based on the content height unless you're dynamically updating the popup content using DOM APIs. You can try one of the following options:

- Avoid directly updating the popup content using DOM APIs; instead, update the `popupContent` prop.
- Set a fixed height for the popup container so that it doesn't change with its content.
- Toggle `isVisible` to false and then true again, allowing the popup to recalculate its position.

**Comment by ashishkabuni** [comment] 2023-12-14 14:20
my popup is showing bottom of the screen, not sure why. can someone tell me how to show it on icon. I am using custom icon

**Comment by ashishkabuni** [comment] 2023-12-14 15:59
Note same code showing popup correctly with version 0.4.7

**Comment by yulinscottkang** [comment] 2023-12-15 02:23
@ashishkabuni, `e.position` could be inaccurate based on your current zoom level. Instead of relying on it for the popup's position, it's better to use `position: e.shapes[0].getCoordinates()` for a more precise longitude and latitude.

```diff
// Set popup options
setPopupOptions({
-  position: e.position,
+ position: e.shapes[0].getCoordinates(),
  showPointer: true,
   content: "<h1>count: 20</h1>",
   closeButton: true,
  draggable: false,
});
```

**Comment by yulinscottkang** [comment] 2024-04-10 02:36
Duplicate of https://github.com/Azure/react-azure-maps/issues/190

**Closed by yulinscottkang** 2024-04-10 02:36 UTC
